services:
  - type: web
    name: ftd-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: "true"
      - key: PORT
        value: "5000"
      - key: MONGODB_URI
        fromDatabase:
          name: ftd-mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "https://ftd-copy.vercel.app,https://ftd-omega.vercel.app"
    autoDeploy: true
    healthCheckPath: /api/health

databases:
  - name: ftd-mongodb
    databaseName: ftd_production
    user: ftd_user
    plan: starter
    region: oregon 